Add bookings
AHeisenberg/java-shareit pull request #3
Opened 2022-09-01 10:25 UTC by AHeisenberg

feat: added functionality to the specifications of the 14th Sprint: add-bookings

2022-09-02 06:55 UTC, kukolev requested changes

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Collection<Booking> findAllByBookerIdAndStartIsAfterOrderByStartDesc(long bookerId, LocalDateTime start);
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStart().isBefore(LocalDateTime.now()) || booking.getEnd().isBefore(LocalDateTime.now()) || booking.getEnd().isBefore(booking.getStart())) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ObjectNotFoundException(String.format("Booking with id %d does not exist", bookingId), "findBookingById"));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidationException(String.format("Reservation with id %d is not pending confirmation", bookingId), "SetStatus");
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new UserHasNoRightsException(String.format("User with id %d has no right to change status", userId), "SetApproved");
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                result = bookingRepository.findAllByBookerIdAndEndIsAfterAndStartIsBefore(userId, LocalDateTime.now(), LocalDateTime.now());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                result = bookingRepository.findAllByBookerIdAndEndIsAfterAndStartIsBefore(userId, LocalDateTime.now(), LocalDateTime.now());
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-02 06:55 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                result = bookingRepository.findAllByItemOwnerIdAndEndIsAfterAndStartIsBefore(userId, LocalDateTime.now(), LocalDateTime.now());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-03 08:22 UTC, AHeisenberg commented
fix: changes made according to Sprint 14 code review

2022-09-03 21:19 UTC, kukolev requested changes

2022-09-03 21:19 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void checkItemExistsById(long itemId) throws ObjectNotFoundException {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-09-03 21:19 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        String errorMessageData = "The start or end date of the booking is incorrect";
Строка используется только в случае, если проверки не прошли. Следовательно строку лучше сделать константой, чтобы не расходовать память при каждом вызове метода.

2022-09-04 10:07 UTC, AHeisenberg commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        String errorMessageData = "The start or end date of the booking is incorrect";
Здравствуйте, спасибо за ревью.

2022-09-04 12:10 UTC, kukolev approved these changes

2022-09-05 09:54 UTC, merged